# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kxmovie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kxmovie

end

target 'KxMovieExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for KxMovieExample
pod ‘Firebase’

end

target 'Sviva Tova' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sviva Tova

end
