# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'kxmovie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kxmovie
   pod 'OneSignal', '>= 2.6.2', '< 3.0'
   pod 'Firebase', '>= 2.5.1'
 pod 'Firebase/Messaging', '>= 2.5.1'
pod 'Firebase/Analytics', '>= 2.5.1'
#pod 'Firebase/Firestore', '>= 2.5.1'
pod 'Firebase/DynamicLinks', '>= 2.5.1'
pod 'GoogleIPhoneUtilities'
end

target 'KxMovieExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KxMovieExample
 pod 'OneSignal', '>= 2.6.2', '< 3.0'
   pod 'Firebase', '>= 2.5.1'
 pod 'Firebase/Messaging', '>= 2.5.1'
pod 'Firebase/Analytics', '>= 2.5.1'
#pod 'Firebase/Firestore', '>= 2.5.1'
pod 'Firebase/DynamicLinks', '>= 2.5.1'
pod 'GoogleIPhoneUtilities'
pod 'gtm-logger'
pod 'IQKeyboardManager' 
end


target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
 pod 'OneSignal', '>= 2.6.2', '< 3.0'
  
end
